#this folder would be created once the code is run
artifacts_root: artifacts


data_ingestion:
  
  #create teh data_ingestion directory
  root_dir: artifacts/data_ingestion

  #get the url of the data zip from the net
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/winequality-data.zip
  
  #store the fetched zip file in this directory
  local_data_file: artifacts/data_ingestion/data.zip
  
  #unizp the file and store here
  unzip_dir: artifacts/data_ingestion



data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt



data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv



model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib



model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json





